#Hugo configuration
title = "wdsfgftr"
baseURL = "https:\/\/wer.dfg.rtre"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
